services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  es:
    build:
      context: ./
      dockerfile: Dockerfile.elasticsearch
    container_name: es
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

  kibana:
    build:
      context: ./
      dockerfile: Dockerfile.kibana
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - es

  logstash:
    build:
      context: ./
      dockerfile: Dockerfile.logstash
    container_name: logstash
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "9600:9600"
      - "5044:5044"
    depends_on:
      - es
#  spring:
#    build:
#      context: ./
#      dockerfile: Dockerfile.spring
#    ports:
#      - "8080:8080"
#    depends_on:
#      - kibana

volumes:
  es-data:
    driver: local