spring:
#  레디스
  data:
    redis:
      port: 6379
      host: redis
      connect-timeout: 3000
  application:
    name: count10shop
  jpa:
    hibernate:
      ddl-auto: none
#      엘라스틱서치
  elasticsearch:
    uris: es:9200
  profiles:
    default: dev

management:
  endpoint:
    health:
      show-details: when_authorized
  endpoints:
    jmx:
      exposure:
        include: health

jwt:
  secret:
    key: ${JWT_SECRET_KEY}