spring:
  data:
    redis:
      port: 6379
      host: redis
      connect-timeout: 3000
    #      엘라스틱서치
    elasticsearch:
      uris: es:9200
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_USER_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect